def generate_complaint(issue, department, reason, severity):
    complaint = f"""
Complaint Report
==============================

Issue Type:
{issue}

Severity:
{severity}

Responsible Department:
{department}

Description:
{reason}

Requested Action:
Kindly inspect the reported location and resolve the issue as soon as possible.

Status:
Pending

Generated By:
Raabta AI (Powered by Google Gemma 4)
"""

    return complaint