print("REPORT FILE LOADED")

from flask import Blueprint, request, jsonify
import os
import json
from werkzeug.utils import secure_filename

from services.gemma_service import detect_issue, generate_complaint, detect_issue_from_text
from services.location_service import get_address
from models.report_model import Report


report_bp = Blueprint("report", __name__)

print("REPORT ROUTE FILE:", __file__)

UPLOAD_FOLDER = os.path.join("/tmp", "uploads") if os.environ.get("VERCEL") else "uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)


@report_bp.route("/report", methods=["POST"], strict_slashes=False)
def test():

    image_path = None

    print(">>> Request received")

    try:

        # -----------------------------
        # Check Image Upload
        # -----------------------------

        if "image" not in request.files:

            return jsonify({
                "status": "error",
                "message": "No image uploaded."
            }), 400

        image = request.files["image"]

        if image.filename == "":

            return jsonify({
                "status": "error",
                "message": "No image selected."
            }), 400

        # -----------------------------
        # Save Image
        # -----------------------------

        image_path = os.path.join(
            UPLOAD_FOLDER,
            secure_filename(image.filename)
        )

        image.save(image_path)

        print("Image saved")

        # -----------------------------
        # Validate Image Integrity
        # -----------------------------
        try:
            from PIL import Image as PILImage
            with PILImage.open(image_path) as img:
                img.verify()
        except Exception as img_err:
            return jsonify({
                "status": "error",
                "message": f"Invalid or corrupt image file: {str(img_err)}"
            }), 400

        # -----------------------------
        # Get User Location
        # -----------------------------

        latitude = request.form.get("latitude")
        longitude = request.form.get("longitude")

        address = None

        if latitude and longitude:

            address = get_address(
                latitude,
                longitude
            )

            try:
                print("Latitude :", latitude)
                print("Longitude:", longitude)
                print("Address  :", address)
            except Exception:
                pass

        else:

            print("No location received.")

        # -----------------------------
        # Step 1 : Gemma Vision
        # -----------------------------

        issue_response = detect_issue(

            image_path=image_path,

            latitude=latitude,

            longitude=longitude,

            address=address

        )

        try:

            issue_data = json.loads(
                issue_response.strip()
            )

            issue = issue_data.get(
                "issue",
                "Unknown"
            )

            reason = issue_data.get(
                "reason",
                ""
            )

            severity = issue_data.get(
                "severity",
                "Medium"
            )

            department = issue_data.get(
                "department",
                "Municipal Corporation"
            )

        except Exception as e:

            print("JSON Parsing Error:", e)

            print("Gemma Raw Response:")
            print(issue_response)

            return jsonify({

                "status": "error",

                "message": "Failed to process AI response."

            }), 500

        # -----------------------------
        # Step 2 : Complaint Generation
        # -----------------------------

        complaint_data = generate_complaint(

            issue=issue,

            reason=reason,

            severity=severity,

            department=department,

            latitude=latitude,

            longitude=longitude,

            address=address

        )

        complaint_subject = complaint_data.get(

            "complaint_subject",

            "Civic Issue Complaint"

        )

        complaint_body = complaint_data.get(

            "complaint_body",

            ""

        )

        # -----------------------------
        # Final Complaint Report
        # -----------------------------

        complaint = f"""
Civic Complaint Report
================================

Subject:
{complaint_subject}

Issue:
{issue}

Reason:
{reason}

Severity:
{severity}

Responsible Department:
{department}

Location:
{address if address else "Location not provided"}

Complaint:

{complaint_body}

--------------------------------

Generated By:
Raabta AI
Powered by Google Gemma 4
"""

        print("Complaint generated")

        # -----------------------------
        # Create Report Object
        # -----------------------------

        report = Report(

            issue,

            department,

            complaint,

            image_path

        )

        # -----------------------------
        # Response
        # -----------------------------

        return jsonify({

            "status": "success",

            "message": "Complaint generated successfully.",

            "location": {

                "latitude": latitude if latitude else "",

                "longitude": longitude if longitude else "",

                "address": address if address else "Location not provided"

            },

            "ai_result": {

                "issue": issue,

                "reason": reason,

                "severity": severity,

                "department": department

            },

            "complaint": {

                "subject": complaint_subject,

                "body": complaint_body

            },

            "report": report.to_dict()

        })

    except Exception as e:
        print("Error processing image report:", e)
        return jsonify({
            "status": "error",
            "message": f"Failed to process image complaint: {str(e)}"
        }), 500

    finally:
        try:
            if image_path and os.path.exists(image_path):
                os.remove(image_path)
        except Exception:
            pass


@report_bp.route("/text-report", methods=["POST"], strict_slashes=False)
def text_report():
    print(">>> Text Report Request received")

    # Get text description
    text = request.form.get("text")
    if not text:
        # Fallback to json if sent as application/json
        if request.is_json:
            text = request.json.get("text")
        
        if not text:
            return jsonify({
                "status": "error",
                "message": "No text complaint provided."
            }), 400

    # Get User Location (optional)
    latitude = request.form.get("latitude") or (request.json.get("latitude") if request.is_json else None)
    longitude = request.form.get("longitude") or (request.json.get("longitude") if request.is_json else None)
    address = request.form.get("location") or (request.json.get("location") if request.is_json else None)

    # Resolve address using get_address if coordinates are provided
    if latitude and longitude and not address:
        try:
            address = get_address(latitude, longitude)
            print("Resolved Address from Coordinates:", address)
        except Exception as e:
            print("Error resolving address:", e)

    try:
        # Step 1 : Gemma Text Analysis
        issue_data = detect_issue_from_text(text)
        
        issue = issue_data.get("issue", "General Civic Issue")
        reason = issue_data.get("reason", text)
        severity = issue_data.get("severity", "Medium")
        department = issue_data.get("department", "Municipal Corporation")

        # Step 2 : Complaint Generation
        complaint_data = generate_complaint(
            issue=issue,
            reason=reason,
            severity=severity,
            department=department,
            latitude=latitude,
            longitude=longitude,
            address=address
        )

        complaint_subject = complaint_data.get(
            "complaint_subject",
            "Civic Issue Complaint"
        )
        complaint_body = complaint_data.get(
            "complaint_body",
            ""
        )

        # Final Complaint Report Formatted String (for Report model / dict consistency)
        complaint_string = f"""Civic Complaint Report
================================

Subject:
{complaint_subject}

Issue:
{issue}

Reason:
{reason}

Severity:
{severity}

Responsible Department:
{department}

Location:
{address if address else "Location not provided"}

Complaint:

{complaint_body}

--------------------------------

Generated By:
Raabta AI
Powered by Google Gemma 4
"""

        print("Text complaint generated successfully")

        # Create Report Object
        report = Report(
            issue,
            department,
            complaint_string,
            None  # No image for text reports
        )

        return jsonify({
            "status": "success",
            "message": "Complaint generated successfully.",
            "location": {
                "latitude": latitude if latitude else "",
                "longitude": longitude if longitude else "",
                "address": address if address else "Location not provided"
            },
            "ai_result": {
                "issue": issue,
                "reason": reason,
                "severity": severity,
                "department": department
            },
            "complaint": {
                "subject": complaint_subject,
                "body": complaint_body
            },
            "report": report.to_dict()
        })

    except Exception as e:
        print("Error processing text report:", e)
        return jsonify({
            "status": "error",
            "message": f"Failed to process complaint: {str(e)}"
        }), 500
