print("REPORT FILE LOADED")

from flask import Blueprint, request, jsonify
import os
import json

from services.gemma_service import detect_issue, generate_complaint
from models.report_model import Report


report_bp = Blueprint("report", __name__)


print("REPORT ROUTE FILE:", __file__)


UPLOAD_FOLDER = "uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)



@report_bp.route("/report", methods=["POST"])
def test():

    print(">>> Request received")


    # -----------------------------
    # Check Image Upload
    # -----------------------------

    if "image" not in request.files:

        return jsonify({

            "status": "error",
            "message": "No image uploaded."

        }), 400



    image = request.files["image"]



    if image.filename == "":

        return jsonify({

            "status": "error",
            "message": "No image selected."

        }), 400



    # -----------------------------
    # Save Image
    # -----------------------------

    image_path = os.path.join(
        UPLOAD_FOLDER,
        image.filename
    )


    image.save(image_path)


    print("Image saved")



    # -----------------------------
    # Step 1: Gemma Vision
    # -----------------------------

    issue_response = detect_issue(
        image_path
    )



    try:

        issue_data = json.loads(
            issue_response.strip()
        )


        issue = issue_data.get(
            "issue",
            "Unknown"
        )


        reason = issue_data.get(
            "reason",
            ""
        )


        severity = issue_data.get(
            "severity",
            "Medium"
        )


        department = issue_data.get(
            "department",
            "Municipal Corporation"
        )



    except Exception as e:


        print(
            "JSON Parsing Error:",
            e
        )


        print(
            "Gemma Raw Response:"
        )


        print(
            issue_response
        )


        return jsonify({

            "status": "error",

            "message": "Failed to process AI response."

        }), 500





    # -----------------------------
    # Step 2: Complaint Generation
    # -----------------------------


    complaint_data = generate_complaint(
    issue=issue,
    reason=reason,
    severity=severity,
    department=department,
    latitude=latitude,
    longitude=longitude,
    address=address
)



    complaint_subject = complaint_data.get(

        "complaint_subject",

        "Civic Issue Complaint"

    )



    complaint_body = complaint_data.get(

        "complaint_body",

        ""

    )





    # -----------------------------
    # Final Complaint Report
    # -----------------------------


    complaint = f"""

Civic Complaint Report
================================

Subject:
{complaint_subject}


Issue:
{issue}


Reason:
{reason}


Severity:
{severity}


Responsible Department:
{department}


Complaint:

{complaint_body}


Generated By:
Raabta AI
Powered by Google Gemma 4

"""



    print(
        "Complaint generated"
    )





    # -----------------------------
    # Create Report Object
    # -----------------------------


    report = Report(

        issue,

        department,

        complaint,

        image_path

    )





    return jsonify({

        "status": "success",

        "message": "Complaint generated successfully.",


        "ai_result": {

            "issue": issue,

            "reason": reason,

            "severity": severity,

            "department": department

        },


        "complaint": {

            "subject": complaint_subject,

            "body": complaint_body

        },


        "report": report.to_dict()

    })